### ISSUE TITLE
RoadMap: Better Boilerplate

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#137]
I think the vision of this repo is to have everything baked in for you to start a good node project from scratch. 

So ideally, I'd like to have good performance optimisations so users can refer to this repo as a good starting point.

Couple of things I can think of:
## Performance
- [ ] font loading example from typekit
- [ ] offline service workers to cache resources? Inspired by [this](https://github.com/mxstbr/react-boilerplate) repo.
- [ ] tightening up the back end
### css
- [x] Better example of CSS. Postcss might be the way to go.
- [ ] Better folder structure?
### Redux
- [x] Abstract data fetching on server-side https://github.com/choonkending/react-webpack-node/issues/134
## Better docs
- [x] Explain data flow
- [ ] Explain login flow
- [ ] Better examples of how to use redux
## Better Testing
- [x] Unit test for components, actions and reducers
## Slim and Stateless
- [x] Have a simpler stateless version of this repo - Stripping out DBs
## Different DB support
- [x] Postgresql
## Developer friendly
- [ ] Flow. Having something like `npm run flow:check` to run in `package.json`

Would appreciate if there are any suggestions that I can add to the list.

**Comment by dzotokan** [comment]
Would LOVE to see a version with [Flow](http://flowtype.org).

**Comment by choonkending** [comment]
Closing for #706
